travis:
  secure:
    BINSTAR_TOKEN: e3YIPffBZgEXvZJ8Kf5kfGvbjEWFE2teSnlTH7CDXwhBxA4ou0PgydPT1GbfP8fHZA+jajFxugrkt9yMFw06IG3BWeb5ZOrMCJo7MkmooU6hPbHX22C6e9KuO1gR1u23SvZhYFOnz9vOMN8hRUYeKW4cY3RImEZ9YyrNzG2i2RtiOkYd8OAxl8S/GZVsbv9icLJb8ferYKPM/Qml7u3wk3Ito6H/VTK9w5C9IP2CuvSQnpE9R4zbhvhO18UY8rPNbZ4vkjU+AJsmxRrqrkDniqPJ/nCmAKp5TXSC3n9btBgO0tRbrVfH+vzx87ltt2csVEIJrlCJLNjXwciQs5cIh03xAllnnPO95rweLilHHpOCgzrsaFkEsrm0aiBDA1emjIAoxA6sg6byenhdVK0XVu7s79zkqCJW82A3JIYKK1RoSZmXgq2bdDtxKC1ssNQLjloMwtmsYmXvF0Yn0wXqgGP7y3EFqrv4XUTVm6TFaZ911MWweX3OYPNkuJKhuWrmDTFLMl0XKNfTLIrzrXAmwl6wMN8m6AEfOVDqvqNkUoWNP7a/URyWjfgvRqBk201wBVav9siBXQpTpD6pkJuK5t/1FM5iXvHted06FJMYy5d4UyBh4ePmQlyRfs9rPjT+qqJO02cZw5y0BRrCTvxe91rH/obcYdsiHkqRYP89bYM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
